name = "tripfldr"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "foldr-db"
database_id = "430628c9-2002-4237-8db4-5830c74b388b"
